{ nsps: 
   { '/': 
      { name: '/',
        server: [Circular],
        sockets: [Object],
        connected: [Object],
        fns: [],
        ids: 0,
        acks: {},
        adapter: [Object],
        _events: [Object] } },
  _path: '/socket.io',
  _serveClient: true,
  _adapter: [Function: Adapter],
  _origins: '*:*',
  sockets: 
   { name: '/',
     server: [Circular],
     sockets: [ [Object] ],
     connected: { YmM27KLbqMoojeoYAAAB: [Object] },
     fns: [],
     ids: 0,
     acks: {},
     adapter: { nsp: [Circular], rooms: [Object], sids: [Object], encoder: {} },
     _events: { connection: [Function] } },
  eio: 
   { clients: { YmM27KLbqMoojeoYAAAB: [Object] },
     clientsCount: 1,
     pingTimeout: 60000,
     pingInterval: 25000,
     upgradeTimeout: 10000,
     maxHttpBufferSize: 100000000,
     transports: [ 'polling', 'websocket' ],
     allowUpgrades: true,
     allowRequest: [Function],
     cookie: 'io',
     ws: 
      { domain: null,
        _events: {},
        _maxListeners: 10,
        options: [Object],
        path: null,
        clients: [] },
     _events: { connection: [Function] } },
  httpServer: 
   { domain: null,
     _events: 
      { connection: [Function: connectionListener],
        clientError: [Function],
        close: [Function],
        upgrade: [Function],
        request: [Function] },
     _maxListeners: 10,
     _connections: 1,
     connections: [Getter/Setter],
     _handle: 
      { fd: 12,
        writeQueueSize: 0,
        onconnection: [Function: onconnection],
        owner: [Circular] },
     _usingSlaves: false,
     _slaves: [],
     allowHalfOpen: true,
     httpAllowHalfOpen: false,
     timeout: 120000,
     _connectionKey: '4:0.0.0.0:4000' },
  engine: 
   { clients: { YmM27KLbqMoojeoYAAAB: [Object] },
     clientsCount: 1,
     pingTimeout: 60000,
     pingInterval: 25000,
     upgradeTimeout: 10000,
     maxHttpBufferSize: 100000000,
     transports: [ 'polling', 'websocket' ],
     allowUpgrades: true,
     allowRequest: [Function],
     cookie: 'io',
     ws: 
      { domain: null,
        _events: {},
        _maxListeners: 10,
        options: [Object],
        path: null,
        clients: [] },
     _events: { connection: [Function] } } }

